excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
  - Carthage*
  - fastlane
line_length: 120
function_body_length: 120

function_parameter_count:
  warning: 8
  error: 10

disabled_rules:
  - control_statement
  - identifier_name
  - todo
  - legacy_constructor # Remove after NSMakeRange is solved for Swift.
  - opening_brace
  - fallthrough
